[build-system]
requires = [
	"setuptools",
	"setuptools-scm",
	"wheel",
]
[project]
name = "GPTCovLet"
requires-python = "3.10.8"
dependencies = [
	"openai",
	"requests",
	"time",
	"selenium",
	"bs4",
]
[project.optional-dependencies]
develop = [
	"black>=23.1.0",
	"pytest=7.2.2",
	"wheel",
]
